Configuration:
    CourtLevel:
      roleClass: AppBundle\Controller\Administration\Configuration\CourtLevelController
      actions: ["view","add","edit","delete"]
      key: court-level

    CourtBuildingStatus:
      roleClass: AppBundle\Controller\Administration\Configuration\CourtBuildingStatusController
      actions: ["view","add","edit","delete"]
      key: court-building-status

    CourtBuildingOwnershipStatus:
      roleClass: AppBundle\Controller\Administration\Configuration\CourtBuildingOwnershipStatusController
      actions: ["view","add","edit","delete"]
      key: court-building-ownership-status

    EconomicActivity:
      roleClass: AppBundle\Controller\Administration\Configuration\EconomicActivityController
      actions: ["view","add","edit","delete"]
      key: economic-activity

    LandOwneshipStatus:
      roleClass: AppBundle\Controller\Administration\Configuration\LandOwnershipStatusController
      actions: ["view","add","edit","delete"]
      key: land-ownership

    TransportMode:
      roleClass: AppBundle\Controller\Administration\Configuration\TransportModeController
      actions: ["view","add","edit","delete"]
      key: transport-mode

    CourtEnvironmentalStatus:
      roleClass: AppBundle\Controller\Administration\Configuration\CourtEnvironmentalStatusController
      actions: ["view","add","edit","delete"]
      key: Court-environmental-status

    LandUse:
      roleClass: AppBundle\Controller\Administration\Configuration\LandUseController
      actions: ["view","add","edit","delete"]
      key: land-use

Location:
    Zone:
      roleClass: AppBundle\Controller\Administration\Location\ZoneController
      actions: ["view","add","edit","delete"]
      key: zone

    Region:
      roleClass: AppBundle\Controller\Administration\Location\RegionController
      actions: ["view","add","edit","delete"]
      key: region

    District:
      roleClass: AppBundle\Controller\Administration\Location\DistrictController
      actions: ["view","add","edit","delete"]
      key: district

    Ward:
      roleClass: AppBundle\Controller\Administration\Location\WardController
      actions: ["view","add","edit","delete"]
      key: ward

    VillageStreet:
      roleClass: AppBundle\Controller\Administration\Location\VillageStreetController
      actions: ["view","add","edit","delete"]
      key: village-street

Courts:
    Court:
      roleClass: AppBundle\Controller\Administration\Court\CourtController
      actions: ["view","add","edit","delete","info","approve","decline"]
      key: court-management

Data-Collectors:
    Data-Collectors:
      roleClass: AppBundle\Controller\Administration\DataCollector\DataCollectorController
      actions: ["view","add","edit","delete","more","info","approve","decline"]
      key: data-collectors

    Data-Collectors-Regions:
      roleClass: AppBundle\Controller\Administration\DataCollector\DataCollectorRegionController
      actions: ["view","add","edit","delete"]
      key: data-collectors-regions

Portal-Users:
    User-Defined-Roles:
      roleClass: AppBundle\Controller\Administration\PortalUsers\RoleController
      actions: ["view","add","edit","delete"]
      key: user-defined-roles

    User-Accounts:
      roleClass: AppBundle\Controller\Administration\PortalUsers\UserController
      actions: ["view","add","edit","delete","info"]
      key: user-accounts